package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/brainplusplus/go-opencv/internal/contract"
)

func RenderABIMarkdown(modules []contract.Module) string {
	var b strings.Builder
	b.WriteString("# go-opencv ABI\n\n")
	b.WriteString("Generated from `internal/contract.Modules`.\n\n")
	b.WriteString("| Module | Owner | API | Symbol | Stability |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, row := range rows(modules) {
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | `%s` | `%s` |\n", row.Module, row.Owner, row.Name, row.Symbol, row.Stability))
	}
	return b.String()
}

func RenderCPPSkeleton(modules []contract.Module) string {
	var b strings.Builder
	b.WriteString("// Code generated by goopencv-gen. DO NOT EDIT.\n")
	b.WriteString("// This file is a backend skeleton for the stable flat ABI.\n\n")
	b.WriteString("#include <stdint.h>\n")
	b.WriteString("#include <stdlib.h>\n\n")
	b.WriteString("extern \"C\" {\n\n")
	seen := map[string]bool{}
	for _, row := range rows(modules) {
		if seen[row.Symbol] {
			continue
		}
		seen[row.Symbol] = true
		if body, ok := cppStub(row.Symbol); ok {
			b.WriteString(body)
			b.WriteString("\n")
			continue
		}
		b.WriteString(fmt.Sprintf("// TODO(%s): implement %s for %s.%s.\n", row.Stability, row.Symbol, row.Module, row.Name))
	}
	b.WriteString("}\n")
	return b.String()
}

type row struct {
	Module    string
	Owner     string
	Name      string
	Symbol    string
	Stability contract.Stability
}

func rows(modules []contract.Module) []row {
	var out []row
	for _, m := range modules {
		for _, f := range m.Functions {
			out = append(out, row{Module: m.Name, Owner: "-", Name: f.Name, Symbol: f.Symbol, Stability: f.Stability})
		}
		for _, r := range m.Resources {
			for _, f := range r.Methods {
				out = append(out, row{Module: m.Name, Owner: r.Name, Name: f.Name, Symbol: f.Symbol, Stability: f.Stability})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Module != out[j].Module {
			return out[i].Module < out[j].Module
		}
		if out[i].Owner != out[j].Owner {
			return out[i].Owner < out[j].Owner
		}
		return out[i].Name < out[j].Name
	})
	return out
}

func cppStub(symbol string) (string, bool) {
	switch symbol {
	case "goopencv_mat_new":
		// Encodes rows/cols/type into the handle for deterministic testing.
		// Returns 0 (null) if the handle would be zero (invalid).
		return `uint64_t goopencv_mat_new(int32_t rows, int32_t cols, int32_t type) {
  uint64_t h = ((uint64_t)(uint32_t)rows << 32) | ((uint64_t)(uint32_t)cols << 16) | ((uint64_t)(uint32_t)type & 0xFFFF);
  return h == 0 ? 1 : h;
}
`, true
	case "goopencv_mat_delete":
		return "int32_t goopencv_mat_delete(uint64_t handle) {\n  (void)handle;\n  return 0;\n}\n", true
	case "goopencv_mat_clone":
		return "uint64_t goopencv_mat_clone(uint64_t handle) {\n  return handle + 1000000;\n}\n", true
	case "goopencv_mat_rows":
		return "int32_t goopencv_mat_rows(uint64_t handle) {\n  return (int32_t)(handle >> 32);\n}\n", true
	case "goopencv_mat_cols":
		return "int32_t goopencv_mat_cols(uint64_t handle) {\n  return (int32_t)((handle >> 16) & 0xFFFF);\n}\n", true
	case "goopencv_mat_type":
		return "int32_t goopencv_mat_type(uint64_t handle) {\n  return (int32_t)(handle & 0xFFFF);\n}\n", true
	case "goopencv_imgproc_cvt_color":
		return "int32_t goopencv_imgproc_cvt_color(uint64_t src, uint64_t dst, int32_t code) {\n  (void)src; (void)dst; (void)code;\n  return 0;\n}\n", true
	case "goopencv_imgproc_resize":
		return "int32_t goopencv_imgproc_resize(uint64_t src, uint64_t dst, int32_t width, int32_t height) {\n  (void)src; (void)dst; (void)width; (void)height;\n  return 0;\n}\n", true
	default:
		return "", false
	}
}
